In [2]:
import pandas as pd
df = pd.read_csv("downloads/60k_core_all.csv")

In [3]:
!pip install bertopic

     |████████████████████████████████| 57 kB 6.3 MB/s             
  Using cached sentence-transformers-2.2.0.tar.gz (79 kB)
  Preparing metadata (setup.py) ... done
  Using cached umap-learn-0.5.2.tar.gz (86 kB)
  Preparing metadata (setup.py) ... done
     |████████████████████████████████| 57 kB 7.9 MB/s             
     |████████████████████████████████| 55 kB 8.6 MB/s              
     |████████████████████████████████| 55 kB 8.2 MB/s              
     |████████████████████████████████| 53 kB 4.8 MB/s              
     |████████████████████████████████| 53 kB 3.0 MB/s              
     |████████████████████████████████| 40 kB 6.5 MB/s              
     |████████████▉                   | 352.9 MB 149.4 MB/s eta 0:00:04

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



     |█████████████████████████▉      | 711.8 MB 150.7 MB/s eta 0:00:02

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



     |██████████████████████████████▏ | 830.9 MB 129.3 MB/s eta 0:00:01

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



     |████████████████████████████████| 881.9 MB 5.9 kB/s              
  Using cached hdbscan-0.8.28.tar.gz (5.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     |████████████████████████████████| 6.4 MB 86.4 MB/s            
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached transformers-4.17.0-py3-none-any.whl (3.8 MB)
     |████████████████████████████████| 23.3 MB 36.3 MB/s            
     |████████████████████████████████| 1.2 MB 74.7 MB/s            
  Using cached huggingface_hub-0.4.0-py3-none-any.whl (67 kB)
  Using cached pynndescent-0.5.6.tar.gz (1.1 MB)
  Preparing metadata (setup.py) ... done
     |████████████████████████████████| 6.5 MB 13.0 MB/s            
  Using cached sacremoses-0.0.47-py2.py3-none-any.whl (895 kB)
     |████████████▋                   | 346.3 MB 131.9 MB/s

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



     |█████████████████████████▌      | 702.0 MB 155.4 MB/s eta 0:00:02

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



     |████████████████████████████████| 881.9 MB 8.3 kB/s              
  Created wheel for hdbscan: filename=hdbscan-0.8.27-cp36-cp36m-linux_x86_64.whl size=805388 sha256=0db727ee96e102a9ad7b85a8adcd28bd2fa03102a3aecbd43d69a910f6f4dd62
  Stored in directory: /home/ec2-user/.cache/pip/wheels/70/52/fe/83ef5a0e879c48df9968d931d41046226e4cb19a166f0223d2
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.0-py3-none-any.whl size=120747 sha256=6ca28ba8e13dcf4dbeca9c7d9e2131f0c49c9e560b367a878c94d32f3959bb02
  Stored in directory: /home/ec2-user/.cache/pip/wheels/ce/2d/86/18ade2fbe66e17694cf8f5667a68d2bd06a65bce42546ea675
  Created wheel for umap-learn: filename=umap_learn-0.5.2-py3-none-any.whl size=82696 sha256=44d5a1b2183b47c64c4c16f96c2ad22bf7614b54775246b8741af4488e4dc6d9
  Stored in directory: /home/ec2-user/.cache/pip/wheels/21/13/d2/20d08b12788c5c75e5e02cba181b9c8f1e4cdc8616aabf9209
  Created wheel for pynndescent: filename=pynndescent-0.5.6-py3-none-any.whl

In [4]:
!pip uninstall umap
!pip install umap-learn

## BERTOPIC

In [5]:
!pip install stop-words

  Preparing metadata (setup.py) ... done
  Created wheel for stop-words: filename=stop_words-2018.7.23-py3-none-any.whl size=32916 sha256=3a6be2b2f1a78653c09f045fd3988110587da39f7e2efd2babd8edb3d86a8e9b
  Stored in directory: /home/ec2-user/.cache/pip/wheels/61/13/fb/bde87253355995b963f6355ca563a614453668bfc1b44fdc54
Successfully built stop-words


In [6]:
from bertopic import BERTopic
m = BERTopic(embedding_model='sentence-transformers/all-mpnet-base-v2', calculate_probabilities=True, verbose=True)

In [7]:
def extract_topics(texts, distance_thresh=0.035, model=m):
    topic_labels = model.transform(texts)[0]
    topic_dict = {}
    for idx, ID in enumerate(topic_labels):
        topics = model.get_topic(ID)
        for t in topics:
            topic = t[0]
            dist = t[1]
            if dist > distance_thresh:
                if not topic_dict.get(topic):
                    topic_dict[topic] = [ texts[idx] ] 
                else:
                    sents = topic_dict[topic] + [texts[idx]]
                    topic_dict[topic] = sents
    return topic_dict

In [8]:
from stop_words import get_stop_words
def get_topic_name(topic_id, m, take=2,):
    ts = m.get_topic(topic_id)
    ts = [word[0] for word in ts if word not in get_stop_words('english')]

    name = ""
    for t in ts[:take]:
        name += t
        name += " "
    return name.strip()

In [17]:
sents1= list(df["text"][:15000])

In [ ]:
topics, probs = m.fit_transform(sents1)
#4:27

Batches:   0%|          | 0/469 [00:00<?, ?it/s]

In [ ]:
4

In [95]:
df["probs"] = [list(reversed(list(np.argpartition(ps, -3)[-3:]))) for ps in probs]

In [12]:
import numpy as np
def stepwise(step, df, f, key):
    l = []
    tn=[]
    for idx in range(step, len(df)+step-1, step):
        m = BERTopic(embedding_model='sentence-transformers/all-mpnet-base-v2', calculate_probabilities=True, verbose=True)
        print(idx-step, idx)# dataframe[idx-step:idx])
        sl = df[idx-step:idx][key]
        batch = m.fit_transform(list(sl))
        l = l + list([batch])
#         print(batch[1])
        probs = [list(reversed(list(np.argpartition(ps, -3)[-3:]))) for ps in batch[1]]
        t_names = [get_topic_name(p[0], m, 3) for p in probs]
        tn += [t_names]
    return l, tn

In [13]:
batches, t_names = stepwise(100, df[:300], m.fit_transform, "text")

0 100


Batches:   0%|          | 0/4 [00:00<?, ?it/s]

2022-03-06 23:17:09,757 - BERTopic - Transformed documents to Embeddings
2022-03-06 23:17:16,863 - BERTopic - Reduced dimensionality with UMAP
2022-03-06 23:17:16,874 - BERTopic - Clustered UMAP embeddings with HDBSCAN


[[2.42044115e-001 1.77939487e-001 2.18994217e-001]
 [8.31364324e-002 1.00456493e-001 7.98794893e-001]
 [1.40430261e-001 1.70191184e-001 3.19327489e-001]
 [1.34516065e-001 1.08736970e-001 6.13532868e-001]
 [9.46661973e-001 1.67602377e-002 2.03596311e-002]
 [6.50953243e-309 8.37590489e-309 1.00000000e+000]
 [9.22908659e-309 7.86359156e-309 1.00000000e+000]
 [8.42743673e-002 1.30648686e-001 6.29388669e-001]
 [7.40858337e-002 7.84560882e-001 1.23212442e-001]
 [1.35860807e-001 1.65708055e-001 6.92046762e-001]
 [8.16703635e-001 5.61621969e-002 7.28492912e-002]
 [6.55665984e-309 1.00000000e+000 7.83796981e-309]
 [1.00000000e+000 6.86875876e-309 7.96542842e-309]
 [1.54136809e-001 2.53603153e-001 2.30124699e-001]
 [7.29099761e-002 8.35424456e-001 9.03095280e-002]
 [7.98620292e-002 7.24268491e-001 8.97350764e-002]
 [1.07942959e-001 4.57913901e-001 2.01758746e-001]
 [1.97790430e-001 2.48788790e-001 3.22283717e-001]
 [1.58935050e-001 2.82657511e-001 2.22921138e-001]
 [1.00000000e+000 6.46130767e-3

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

2022-03-06 23:17:23,387 - BERTopic - Transformed documents to Embeddings
2022-03-06 23:17:25,851 - BERTopic - Reduced dimensionality with UMAP
2022-03-06 23:17:25,861 - BERTopic - Clustered UMAP embeddings with HDBSCAN


[[4.38747435e-002 2.17835200e-001]
 [1.00000000e+000 5.36604004e-310]
 [1.00000000e+000 5.47306000e-310]
 [3.22227103e-002 6.05810000e-001]
 [7.56839045e-001 2.16418028e-002]
 [9.22161727e-001 1.17710689e-002]
 [9.18189990e-001 1.57428051e-002]
 [1.00000000e+000 5.42417355e-310]
 [9.85556044e-001 1.37244380e-002]
 [1.00000000e+000 5.46481641e-310]
 [9.45694982e-001 1.11732841e-002]
 [1.00000000e+000 5.19347690e-310]
 [8.83728630e-001 2.27399412e-002]
 [7.05002289e-001 1.35411465e-002]
 [1.00000000e+000 5.38086615e-310]
 [9.59815372e-001 2.09239715e-002]
 [1.00000000e+000 5.45209541e-310]
 [9.28821666e-001 7.86946518e-003]
 [1.00000000e+000 5.17565506e-310]
 [5.56667413e-002 5.93670100e-001]
 [7.74911227e-001 1.58487971e-002]
 [6.09657982e-001 2.55610650e-002]
 [5.20231137e-001 2.62969411e-002]
 [4.27896839e-002 1.95859723e-001]
 [6.95893354e-001 1.80660019e-002]
 [7.07283486e-001 2.16156730e-002]
 [8.38633755e-001 1.73735549e-002]
 [8.95117917e-001 1.31987592e-002]
 [1.00000000e+000 5.

ValueError: kth(=-1) out of bounds (2)

In [80]:
def flatten(l):
    return [item for sublist in l for item in sublist]


In [ ]:
t =[]
ps = []
for batch in batches:
    #print(batch[0])
    t += [batch[0]]
    ps += [batch[1]]
#        a+=[t]

a = [flatten(t), flatten(ps)]
len(a), len(a[0])

(2, 66547)

In [ ]:
topics,probs = a

In [ ]:
# td = extract_topics(sentences)

In [ ]:
df["topic_id"] = topics

In [94]:
import numpy as np

In [102]:
df["probs"].map(type).unique()

array([<class 'list'>], dtype=object)

In [104]:
m.get_topic()

False

In [101]:

[word[0] for word in m.get_topic(14) if word not in get_stop_words('english')]

['amyotrophic',
 'als',
 'sclerosis',
 'neuron',
 'neurons',
 'neurodegenerative',
 'spinal',
 'degeneration',
 'death',
 'neurone']

In [ ]:
df["topic_name"] = df["probs"].apply(lambda p: get_topic_name(p[0], 3))

In [237]:
df = df.rename(columns={"sentence_id": "problem_id"})

In [2]:
df

first_sent  \
0                              Liu and Mertz (Genes Dev.   
1      Rett syndrome (RTT), a neurodevelopmental diso...   
2      Estimating optimal sample size for microbiolog...   
3      The antiphospholipid syndrome is a thrombotic ...   
4      Alcohol dependence (AD) is a complex disorder ...   
...                                                  ...   
42196  Autism spectrum disorder (ASD) is a common neu...   
42197  This paper revisits the problem of the readine...   
42198                  Thyroid cancer is a rare disease.   
42199  Hyperosmolar hyperglycaemic state (HHS) is a m...   
42200         Craniopharyngiomas are difficult to treat.   

                                    doi   coreId  \
0      10.1128/MCB.25.15.6303-6313.2005  3717551   
1                        10.1086/382228  3710391   
2      10.1128/AEM.69.10.6174-6178.2003  3286476   
3                                   NaN  8064782   
4                                   NaN  8674979   
...                                 ...      ...   
42196                               NaN  8273706   
42197                               NaN  8689613   
42198                               NaN  8126095   
42199                               NaN  8696563   
42200                               NaN  8729638   

                                     oai  \
0      oai:pubmedcentral.nih.gov:1190326   
1      oai:pubmedcentral.nih.gov:1182264   
2       oai:pubmedcentral.nih.gov:201250   
3      oai:pubmedcentral.nih.gov:2398067   
4      oai:pubmedcentral.nih.gov:3266269   
...                                  ...   
42196  oai:pubmedcentral.nih.gov:2662567   
42197  oai:pubmedcentral.nih.gov:3291942   
42198  oai:pubmedcentral.nih.gov:2466601   
42199  oai:pubmedcentral.nih.gov:3302717   
42200  oai:pubmedcentral.nih.gov:3356029   

                                                   title  
0      Binding of hnRNP L to the Pre-mRNA Processing ...  
1      X-Chromosome Inactivation Patterns Are Unbalan...  
2      A Model To Estimate the Optimal Sample Size fo...  
3      Antiphospholipid syndrome in a patient with ra...  
4      Genome-Wide Association Study of Copy Number V...  
...                                                  ...  
42196  The genetic and neurobiologic compass points t...  
42197  On the Relevance of Using Open Wireless Sensor...  
42198                Thyroid carcinoma and its treatment  
42199  A case of hyperosmolar hyperglycaemic state wi...  
42200  Outcome of Endoscopy-Assisted Microscopic Exte...  

[42201 rows x 5 columns]